--- 
AWSTemplateFormatVersion: "2010-09-09"
Description: Dispatcher Lambda and SQS template
Parameters: 
  LambdaSource: 
    Description: "Location of Lambda code in s3"
    Type: String
  QueueName: 
    Description: "Name for SQS queue"
    Type: String
  RouteURL:
    Description: URL of consumer to route message to 
    Type: String
Resources: 
  MySQSQueueFunction: 
    Properties: 
      Code: 
        S3Bucket: lambda.bucket.moodle
        S3Key: 0099c60070693ac2f7321ad1b2894d3f
      Handler: main
      Role: 
        ? "Fn::GetAtt"
        : 
          - MySQSQueueFunctionRole
          - Arn
      Runtime: go1.x
      Timeout: 3
      Environment:
        Variables:
          Region: !Sub ${AWS::Region}
          RouteURL: !Ref RouteURL
      Tags: 
        - 
          Key: "lambda:createdBy"
          Value: SAM
    Type: "AWS::Lambda::Function"
  MySQSQueueFunctionMySQSEvent: 
    Properties: 
      BatchSize: 10
      EventSourceArn: 
        ? "Fn::GetAtt"
        : 
          - MySqsQueue
          - Arn
      FunctionName: 
        Ref: MySQSQueueFunction
    Type: "AWS::Lambda::EventSourceMapping"
  MySQSQueueFunctionRole: 
    Properties: 
      AssumeRolePolicyDocument: 
        Statement: 
          - 
            Action: 
              - "sts:AssumeRole"
            Effect: Allow
            Principal: 
              Service: 
                - lambda.amazonaws.com
        Version: "2012-10-17"
      ManagedPolicyArns: 
        - "arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"
        - "arn:aws:iam::aws:policy/service-role/AWSLambdaSQSQueueExecutionRole"
    Type: "AWS::IAM::Role"
  MySqsQueue: 
    Properties: 
      QueueName: 
        Ref: QueueName
    Type: "AWS::SQS::Queue"
