AWSTemplateFormatVersion: '2010-09-09'
Description: Example of processing messages on an SQS queue with Lambda
Parameters:
  LambdaSource:
    Description: Location of Lambda code in s3
    Type: String
  QueueName:
    Description: Name for SQS queue
    Type: String
Resources:
  MySQSQueueFunction:
    Properties:
      Code:
        S3Bucket: !Ref: LambdaSource
        S3Key: 15a842900881edb9e97d945c4394d875
        # ZipFile: String
        
      Events:
        MySQSEvent:
          Properties:
            BatchSize: 10
            Queue:
              Fn::GetAtt:
              - MySqsQueue
              - Arn
          Type: SQS
      Handler: index.handler
      Runtime: nodejs8.10
    Type: AWS::Serverless::Function
  MySqsQueue:
    Properties:
      QueueName:
        Ref: QueueName
    Type: AWS::SQS::Queue
Transform: AWS::Serverless-2016-10-31
